# Site settings
title:       Wilfred Hughes::Blog
email:       me@wilfred.me.uk
author:      Wilfred Hughes
description: "programming, language design, and human factors"
baseurl:     ""
url:         "https://www.wilfred.me.uk"
date_format: "%e %B %Y"
future: true

# Search engine verification (leave blank to omit the meta tag)
google_verification:
bing_verification:

# Optional features
animated:           true
show_related_posts: true
show_social_icons:  true
enable_anchorjs:    true

# Social icons
github_username:  wilfred
twitter_username: _wilfredh

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'

    # Jekyll doesn't have any default cleverness around finding
    # related posts. There are plugins, but GitHub only supports
    # uncustomised Jekyll.
    related_posts:  'Recent Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Your email address'
    content:  'Your message'
    subject:  'New message from wilfred.me.uk'
    submit:   'Send'
  thanks: 'Email sent, thanks.'
  og_locale: 'en_GB'

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
paginate: 4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - PIXYLL_LICENSE.txt
  - README.md
  - Rakefile
  - post_ideas.org
  - vendor
