# Site settings
title:       Wilfred Hughes::Blog
email:       me@wilfred.me.uk
author:      Wilfred Hughge
description: "programming, language design, and human factors"
baseurl:     ""
url:         "http://www.wilfred.me.uk"
date_format: "%e %B %Y"
future: true

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-3370763-1
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: wilfred
bitbucket_username:
stackoverflow_id:
twitter_username: _wilfredh
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'

    # Jekyll doesn't have any default cleverness around finding
    # related posts. There are plugins, but GitHub only supports
    # uncustomised Jekyll.
    related_posts:  'Recent Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Your email address'
    content:  'Your message'
    subject:  'New message from wilfred.me.uk'
    submit:   'Send'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Email sent, thanks.'
  og_locale: 'en_GB'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /blog/:year/:month/:day/:title/
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
